services:
  _defaults:
    autowire: true
    autoconfigure: true

  Krabo\IsotopePackagingSlipBarcodeScannerBundle\Controller\BarcodePackageslipController: ~
  Krabo\IsotopePackagingSlipBarcodeScannerBundle\EventListener\BackendMenuListener: ~
  Krabo\IsotopePackagingSlipBarcodeScannerBundle\Twig\TwigExtension: ~
  krabo.isotopepackagingslipbarcodescanner.helper:
    class: Krabo\IsotopePackagingSlipBarcodeScannerBundle\Helper\PickupShopHelper
    public: true